actualizacion de la app movil

diff --git a/.github/workflows/DeployItch.yml b/.github/workflows/DeployItch.yml
--- a/.github/workflows/DeployItch.yml
+++ b/.github/workflows/DeployItch.yml
@@ -43,34 +43,27 @@ jobs:
           echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV
 
       - name: Build APK using EAS
+        id: build-apk
         env:
           EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
-        run: eas build --platform android --profile production --non-interactive
-
-      - name: Fetch APK or AAB URL from Logs
-        id: fetch-url
         run: |
-          OUTPUT=$(eas build:list --json --non-interactive)
-          if [ -z "$OUTPUT" ]; then
-            echo "No builds found in the list. Stopping the workflow."
-            exit 1
-          fi
-          URL=$(echo $OUTPUT | jq -r '[.[] | select(.status == "FINISHED")][0].artifacts.buildUrl')
-          if [ "$URL" = "null" ] || [ -z "$URL" ]; then
-            echo "No URL found for the latest build. Stopping the workflow."
-            exit 1
-          fi
-          echo "APK_OR_AAB_URL=$URL" >> $GITHUB_ENV
-          echo "Found URL: $URL"
+          eas build --platform android --profile production --non-interactive | tee build-log.txt
 
-      - name: Download APK or AAB
+      - name: Extract APK URL from Logs
+        id: extract-url
+        run: |
+          URL=$(grep -oP 'https://expo.dev/artifacts/eas/\S+\.apk' build-log.txt | tail -1)
+          if [ -z "$URL" ]; then
+            echo "Failed to extract APK URL from build logs."
+            exit 1
+          fi
+          echo "APK_URL=$URL" >> $GITHUB_ENV
+          echo "Found APK URL: $URL"
+
+      - name: Download APK
         run: |
           mkdir -p debug
-          if [ -z "$APK_OR_AAB_URL" ]; then
-            echo "No URL provided. Exiting."
-            exit 1
-          fi
-          curl -o debug/clinicaJireh.apk-or-aab "$APK_OR_AAB_URL"
+          curl -o debug/clinicaJireh.apk "$APK_URL"
 
       - name: Install Butler
         run: |
@@ -83,10 +76,10 @@ jobs:
         env:
           BUTLER_API_KEY: ${{ secrets.ITCH_API_KEY }}
         run: |
-          if [ -f "debug/clinicaJireh.apk-or-aab" ]; then
-            echo "Artifact file found. Deploying to Itch.io..."
-            butler push debug/clinicaJireh.apk-or-aab abelardo20200782/proyectojireh:android
+          if [ -f "debug/clinicaJireh.apk" ]; then
+            echo "APK file found. Deploying to Itch.io..."
+            butler push debug/clinicaJireh.apk abelardo20200782/proyectojireh:android
           else
-            echo "Artifact file not found. Stopping deployment."
+            echo "APK file not found. Stopping deployment."
             exit 1
           fi
